# Generated by Django 2.0 on 2017-12-05 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20171205_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表日期'),
        ),
    ]
