# Generated by Django 2.0 on 2017-12-05 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_massage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='posttime'),
        ),
    ]
