# Generated by Django 2.0 on 2017-12-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headImg', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
