# Generated by Django 2.0 on 2017-12-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_imag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imag',
            new_name='Img',
        ),
    ]
