# Generated by Django 2.0 on 2017-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_auto_20171209_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='SayGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('foodid', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='dish',
            name='headImg',
            field=models.FileField(default=1, upload_to='./upload/'),
            preserve_default=False,
        ),
    ]
