# Generated by Django 2.0 on 2017-12-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_auto_20171209_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='headImg',
            field=models.FileField(upload_to='./../../ReactFinal/app/elment'),
        ),
    ]
